import { CarouselArtboard } from "./carousel-artboard";

// Renders the body of a draft based on its format. Each format has its
// own component so we don't end up with one giant if/else.

type Brief = {
  intent: string;
  audience: string;
  pillar: string;
  hookFramework: string;
};

// Hero image, rendered uniformly across single-posts, newsletters, and
// reel/story frames. Capped at 280px wide so the card stays scannable
// — full size would push the action buttons two screens down. Falls
// back to a neutral placeholder while the image is still being
// generated by Replicate (echo backfills these in the background —
// see backfillImagesForDraft in agents/echo.ts).
function HeroImage({
  url,
  aspect = "1/1",
}: {
  url: string | null | undefined;
  aspect?: string;
}) {
  if (!url) {
    return (
      <div
        className="bg-bg border-hairline border-border rounded-md flex items-center justify-center mb-md max-w-[280px]"
        style={{ aspectRatio: aspect, width: "100%" }}
      >
        <div className="text-xs text-ink4 font-mono">drawing image…</div>
      </div>
    );
  }
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={url}
      alt=""
      className="rounded-md mb-md object-cover max-w-[280px] w-full"
      style={{ aspectRatio: aspect }}
    />
  );
}

function BriefRow({ brief }: { brief: Brief | null }) {
  if (!brief) return null;
  return (
    <div className="flex items-center gap-md flex-wrap mb-md">
      <span className="text-[11px] text-ink4">
        intent: <span className="text-ink2">{brief.intent}</span>
      </span>
      <span className="text-[11px] text-ink4">
        for: <span className="text-ink2">{brief.audience}</span>
      </span>
      <span className="text-[11px] text-ink4">
        pillar: <span className="text-ink2">{brief.pillar}</span>
      </span>
      <span className="text-[11px] text-ink4">
        hook: <span className="text-ink2">{brief.hookFramework}</span>
      </span>
    </div>
  );
}

function HashtagRow({ tags }: { tags: string[] | undefined }) {
  if (!tags || tags.length === 0) return null;
  return (
    <p className="text-xs text-ink4 mt-md">
      {tags.map((t) => `#${t.replace(/^#/, "")}`).join(" ")}
    </p>
  );
}

export function DraftBody({
  format,
  content,
}: {
  format: string;
  content: unknown;
}) {
  if (!content || typeof content !== "object") {
    return <p className="text-sm text-ink3">(empty)</p>;
  }
  const c = content as Record<string, unknown>;
  const brief = (c.brief as Brief | undefined) ?? null;

  if (format === "SINGLE_POST") {
    const hero = c.heroImage as { url?: string | null } | undefined;
    return (
      <>
        <BriefRow brief={brief} />
        <HeroImage url={hero?.url} aspect="1/1" />
        <p className="text-md font-medium leading-relaxed mb-sm">
          {(c.hook as string) ?? ""}
        </p>
        <p className="text-md leading-relaxed whitespace-pre-wrap text-ink2">
          {(c.body as string) ?? ""}
        </p>
        {c.cta ? (
          <p className="text-md text-ink mt-md font-medium">
            {String(c.cta)}
          </p>
        ) : null}
        <HashtagRow tags={c.hashtags as string[] | undefined} />
      </>
    );
  }

  if (format === "CAROUSEL") {
    const cover = (c.coverSlide ?? {
      title: "(no cover)",
      subtitle: null,
      visualDirection: "",
      palette: "ink",
    }) as Parameters<typeof CarouselArtboard>[0]["cover"];
    const body = (c.bodySlides ?? []) as Parameters<
      typeof CarouselArtboard
    >[0]["body"];
    const closer = (c.closerSlide ?? {
      title: "",
      body: "",
      cta: null,
      palette: "ink",
    }) as Parameters<typeof CarouselArtboard>[0]["closer"];
    return (
      <>
        <BriefRow brief={brief} />
        <div className="text-xs text-ink4 mb-md">
          carousel · {body.length + 2} slides
        </div>
        <CarouselArtboard cover={cover} body={body} closer={closer} />
        {c.caption ? (
          <p className="text-md leading-relaxed whitespace-pre-wrap text-ink2 mt-lg">
            {String(c.caption)}
          </p>
        ) : null}
        <HashtagRow tags={c.hashtags as string[] | undefined} />
      </>
    );
  }

  if (format === "REEL_SCRIPT") {
    const beats = (c.beats as
      | {
          timestamp: string;
          onScreenText: string;
          voiceover: string | null;
          bRoll: string;
          imageUrl?: string | null;
        }[]
      | undefined) ?? [];
    return (
      <>
        <BriefRow brief={brief} />
        <div className="text-xs text-ink4 mb-sm">
          reel · {beats.length} beats
        </div>
        <p className="text-md font-medium mb-md">
          🎬 hook (0:00): {(c.hook as string) ?? ""}
        </p>
        <div className="border-l-2 border-border pl-md flex flex-col gap-md mb-md">
          {beats.map((b, i) => (
            <div key={i} className="flex gap-md">
              {b.imageUrl ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={b.imageUrl}
                  alt=""
                  className="shrink-0 w-[80px] aspect-[9/16] rounded-md object-cover"
                />
              ) : null}
              <div className="flex-1 min-w-0">
                <div className="font-mono text-xs text-aliveDark mb-xs">
                  {b.timestamp}
                </div>
                <div className="text-md font-medium mb-xs">
                  on-screen: {b.onScreenText}
                </div>
                {b.voiceover ? (
                  <div className="text-sm text-ink2 mb-xs">
                    voiceover: {b.voiceover}
                  </div>
                ) : null}
                <div className="text-sm text-ink3 italic">b-roll: {b.bRoll}</div>
              </div>
            </div>
          ))}
        </div>
        {c.audioMood ? (
          <p className="text-xs text-ink4 mb-md">
            audio · {String(c.audioMood)}
          </p>
        ) : null}
        {c.caption ? (
          <p className="text-md text-ink2 whitespace-pre-wrap">
            {String(c.caption)}
          </p>
        ) : null}
        <HashtagRow tags={c.hashtags as string[] | undefined} />
      </>
    );
  }

  if (format === "EMAIL_NEWSLETTER") {
    const sections = (c.sections as
      | { heading: string | null; body: string }[]
      | undefined) ?? [];
    const cta = c.cta as
      | { label: string; intent: string; link: string | null }
      | undefined;
    const hero = c.heroImage as { url?: string | null } | undefined;
    return (
      <>
        <BriefRow brief={brief} />
        <HeroImage url={hero?.url} aspect="16/9" />
        <div className="text-xs text-ink4 mb-sm">email</div>
        <div className="bg-bg border-hairline border-border rounded-md p-md mb-md">
          <div className="text-[11px] text-ink4 mb-xs">subject</div>
          <div className="text-md font-medium mb-md">
            {(c.subject as string) ?? ""}
          </div>
          <div className="text-[11px] text-ink4 mb-xs">preheader</div>
          <div className="text-sm text-ink3">
            {(c.preheader as string) ?? ""}
          </div>
        </div>
        {sections.map((s, i) => (
          <div key={i} className="mb-md">
            {s.heading ? (
              <div className="text-md font-medium mb-xs">{s.heading}</div>
            ) : null}
            <p className="text-md leading-relaxed whitespace-pre-wrap text-ink2">
              {s.body}
            </p>
          </div>
        ))}
        {cta ? (
          <div className="mt-lg pt-md border-t-hairline border-border2">
            <div className="text-[11px] text-ink4 mb-xs">
              cta · {cta.intent}
            </div>
            <div className="text-md font-medium">{cta.label}</div>
            {cta.link ? (
              <div className="font-mono text-xs text-ink4 mt-xs break-all">
                {cta.link}
              </div>
            ) : null}
          </div>
        ) : null}
      </>
    );
  }

  if (format === "STORY_SEQUENCE") {
    const frames = (c.frames as
      | {
          text: string;
          interaction: string;
          visualDirection: string;
          imageUrl?: string | null;
        }[]
      | undefined) ?? [];
    return (
      <>
        <BriefRow brief={brief} />
        <div className="text-xs text-ink4 mb-md">
          stories · {frames.length} frames
        </div>
        <div className="flex gap-sm overflow-x-auto pb-sm">
          {frames.map((f, i) => (
            <div
              key={i}
              className="shrink-0 w-[150px] aspect-[9/16] rounded-md p-md flex flex-col justify-between text-white relative overflow-hidden"
              style={{
                backgroundImage: f.imageUrl
                  ? `linear-gradient(rgba(0,0,0,0.25), rgba(0,0,0,0.55)), url(${f.imageUrl})`
                  : undefined,
                backgroundColor: f.imageUrl ? undefined : "#1A1815",
                backgroundSize: "cover",
                backgroundPosition: "center",
              }}
            >
              <div className="text-[10px] opacity-70">{i + 1}/{frames.length}</div>
              <div className="text-sm font-medium leading-tight">{f.text}</div>
              <div>
                {f.interaction !== "none" ? (
                  <div className="text-[10px] opacity-70 mb-xs">
                    {f.interaction.toLowerCase()}
                  </div>
                ) : null}
                <div className="text-[10px] opacity-60 leading-snug">
                  {f.visualDirection.slice(0, 60)}
                </div>
              </div>
            </div>
          ))}
        </div>
      </>
    );
  }

  // Fallback
  return (
    <pre className="text-xs text-ink3 overflow-x-auto whitespace-pre-wrap">
      {JSON.stringify(content, null, 2)}
    </pre>
  );
}

