// BrandMark — renders the business's mark SVG (or a fallback orb)
// with optional breathing + pulse rings. This is the per-business
// signature — appears in every composition's intro / outro.

import { useCurrentFrame, interpolate, Easing } from "remotion";

const FALLBACK_MARK_INNER = `
  <radialGradient id="orb-grad" cx="30%" cy="25%" r="80%">
    <stop offset="0%" stop-color="#5a5a5a"/>
    <stop offset="35%" stop-color="#2a2a2a"/>
    <stop offset="100%" stop-color="#000"/>
  </radialGradient>
  <circle cx="50" cy="50" r="48" fill="url(#orb-grad)"/>
  <ellipse cx="36" cy="32" rx="10" ry="6" fill="#fff" fill-opacity="0.32" transform="rotate(-25 36 32)"/>`;

type Props = {
  // Inner SVG fragment (no outer <svg> wrapper). Use the BrandKit's
  // logoTemplates.mark, run through extractMarkInner first.
  markInner?: string;
  // Pixel size of the mark. Default 96.
  size?: number;
  // Frame at which the mark first appears.
  startFrame?: number;
  // Frame across which it fades in. Default 14.
  durationFrames?: number;
  // Whether to show the breathing animation after entrance. Default true.
  breathing?: boolean;
  // Whether to render the two faint pulse rings. Default false (only
  // turn on for the closing card / intro hold to avoid visual noise).
  rings?: boolean;
  // Hex color used for the rings. Default a soft grey.
  ringColor?: string;
  style?: React.CSSProperties;
};

export function BrandMark({
  markInner,
  size = 96,
  startFrame = 0,
  durationFrames = 14,
  breathing = true,
  rings = false,
  ringColor = "rgba(17, 17, 17, 0.18)",
  style,
}: Props) {
  const frame = useCurrentFrame();
  const localFrame = Math.max(0, frame - startFrame);

  // Entrance: opacity + scale together.
  const entrance = interpolate(localFrame, [0, durationFrames], [0, 1], {
    extrapolateRight: "clamp",
    easing: Easing.out(Easing.cubic),
  });

  // Breathing: gentle ±3% scale once the mark has fully entered.
  const breatheT = Math.max(0, localFrame - durationFrames);
  const breatheCycle = (breatheT / 96) % 1; // 96 frames = ~3.2s @ 30fps
  const breathePhase = Math.sin(breatheCycle * Math.PI * 2);
  const breatheScale = breathing ? 1 + breathePhase * 0.03 : 1;

  // Ring pulse: same 96-frame cycle. Two rings, second offset by 33%.
  const ringPhase = (localFrame / 96) % 1;
  const ringPhaseB = (ringPhase + 0.33) % 1;
  const ringScale = (p: number) => 1 + p * 1.2;
  const ringOpacity = (p: number) =>
    interpolate(p, [0, 1], [0.5, 0], { extrapolateRight: "clamp" });

  return (
    <div
      style={{
        position: "relative",
        width: size,
        height: size,
        opacity: entrance,
        transform: `scale(${0.85 + entrance * 0.15})`,
        ...style,
      }}
    >
      {rings ? (
        <>
          <div
            style={{
              position: "absolute",
              inset: 0,
              borderRadius: "50%",
              border: `0.5px solid ${ringColor}`,
              transform: `scale(${ringScale(ringPhase)})`,
              opacity: ringOpacity(ringPhase),
              pointerEvents: "none",
            }}
          />
          <div
            style={{
              position: "absolute",
              inset: 0,
              borderRadius: "50%",
              border: `0.5px solid ${ringColor}`,
              transform: `scale(${ringScale(ringPhaseB)})`,
              opacity: ringOpacity(ringPhaseB),
              pointerEvents: "none",
            }}
          />
        </>
      ) : null}
      <div
        style={{
          width: "100%",
          height: "100%",
          transform: `scale(${breatheScale})`,
          transformOrigin: "center",
        }}
        // SVG markup is sourced from the BrandKit; safe because it's
        // generated by our pipeline, not user-supplied raw HTML.
        dangerouslySetInnerHTML={{
          __html: `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">${markInner ?? FALLBACK_MARK_INNER}</svg>`,
        }}
      />
    </div>
  );
}
